#!/usr/bin/env python3
from  matplotlib.patches import Patch
import networkx as nx
import matplotlib.pyplot as plt
from matplotlib.ticker import NullLocator

from tree import create_graph as original_tree

try:
    from networkx.drawing.nx_agraph import graphviz_layout
except ImportError:
    raise ImportError("This example needs Graphviz and either PyGraphviz or Pydot")

import pandas
propagationData = pandas.read_csv('UpdatedPropagationRecords.csv')
alarmData       = pandas.read_csv('smoothed_alarm_strengths.csv')

def visualize():
    pos = graphviz_layout(original_tree()[0], prog='twopi', args='')
    for second in range(163):
        interactions = propagationData[(propagationData.TimeForAlarm <= second)]
        alarmSecondData = alarmData[(alarmData.Frame < (second + 1) * 30) & (alarmData.Frame > (second) * 30)]
        for frame in range(29):
            alarmFrameData = alarmSecondData.iloc[frame]
            G = nx.DiGraph()
            colorMap = []
            whiteLabels = dict()
            blackLabels = dict()
            alarmedAnts = [(i, alarmFrameData['V' + str(i)]) for i in range(1, 62)]
            alarmedAnts = sorted(alarmedAnts, key=lambda t : t[1])
            for i, strength in alarmedAnts:
                #if i == 23 or (strength < 0.3 or strength > 0.9) and i not in {20, 12, 9}:
                if strength > 0.5:
                    blackLabels[i] = str(i)
                else:
                    whiteLabels[i] = str(i)
                G.add_node(i)
                colorMap.append(strength)
            for index, row in interactions.iterrows():
                source, dest = row['AlarmedFrom'], row['Alarmed']
                if not row['Self-Excitation']:
                    G.add_edge(source, dest)

            plt.subplots_adjust(top = 1, bottom = 0, right = 1, left = 0,
                    hspace = 0, wspace = 0)

            fsize = 14
            nx.draw(G, pos, node_color=colorMap, node_size=500, cmap=plt.cm.Reds_r)
            nx.draw_networkx_labels(G, pos, labels=whiteLabels, font_size=fsize, font_color='w')
            nx.draw_networkx_labels(G, pos, labels=blackLabels, font_size=fsize)
            print(second * 30 + frame)
            plt.savefig('abstract_frames/{}.png'.format(str(second * 30 + frame).rjust(4, '0')), dpi=300, bbox_inches='tight')
            plt.clf()

visualize()
