#!/usr/bin/env python3

from PIL import Image

image_name = lambda d, frame : '{}frames/{}.png'.format(d, str(frame).rjust(4, '0'))

for frame in range(1700):
    print(frame)
    try:
        imname = image_name('combined_', frame)
        old_im = Image.open(imname)
        old_size = old_im.size
        new_size = (old_size[0], 800)
        new_im = Image.new("RGB", new_size)   ## luckily, this is already black!
        new_im.paste(old_im, (0, 0))
        imname = image_name('new_combined_', frame)
        new_im.save(imname)
    except KeyboardInterrupt:
        raise
    except Exception as e:
        print(e)
        pass
