#!/usr/bin/env python3
from  matplotlib.patches import Patch
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

import pandas

calm_color  = (66/255, 134/255, 1.0)
alert_color = (244/255, 182/255, 66/255)
alarm_color = (178/255, 54/255, 32/255)

alarmData = pandas.read_csv('smoothed_alarm_strengths.csv')

def visualize():
    sns.set(font_scale=2.0)
    for second in range(163):
        alarmSecondData = alarmData[(alarmData.Frame < (second + 1) * 30) & (alarmData.Frame > (second) * 30)]
        for frame in range(29):
            if second * 30 + frame >= 848:
                alarmFrameData = list(alarmSecondData.iloc[frame])
                alarmed = [x for x in alarmFrameData if x > .74  and x <= 1.0]
                calm    = [x for x in alarmFrameData if x <= .74]
                fig, ax = plt.subplots()
                kwargs = dict(kde=False, rug=True, ax=ax)
                sns.distplot(alarmed, color=alarm_color, **kwargs, bins=[0.74, 0.82, 0.91, 1.0])#3, )
                sns.distplot(calm,    color=calm_color,  **kwargs, bins=[0.0, 0.105, 0.21, 0.315, 0.42, 0.525, 0.63, 0.74])#7, )
                ax.set_title('Alarm Distribution')
                ax.set_xlim((0, 1))
                ax.set_ylim((0, 61))
                ax.set_xlabel('Alarm Strength')
                ax.set_ylabel('Number of Ants in Bin')

                plt.subplots_adjust(top = 1, bottom = 0, right = 1, left = 0,
                        hspace = 0, wspace = 0)
                plt.margins(0, 0)
                matplotlib.rcParams.update({'font.size': 14})
                print(second * 30 + frame)
                plt.savefig('distribution_frames/{}.png'.format(str(second * 30 + frame).rjust(4, '0')), dpi=300, bbox_inches='tight', pad_inches=0)
                plt.clf()

visualize()
