#!/usr/bin/env python3

# Original Author: Aric Hagberg (hagberg@lanl.gov)
# Edited by Lucas Saldyt

import pandas
import numpy as np

from matplotlib.transforms import Bbox
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import networkx as nx


alarmData = pandas.read_csv('alarm_strengths.csv')
physicalData = [item for item in pandas.read_csv('physical_data.csv').groupby('frames')]
propagationData = pandas.read_csv('propogation_new.csv')


for index, row in alarmData.iterrows():
    G = nx.Graph()
    colorMap = []

    frame = int(row['Frame'])
    frameData = physicalData[frame][1]
    interactions = propagationData[(((propagationData.frame - 6) * 30 < frame)
                                 & (((propagationData.frame - 3) * 30) > frame))]

    img = mpimg.imread('reference_frames/output_{}.png'.format(str(frame).rjust(4, '0')))
    plt.imshow(img)

    for i in range(1, 62):
        antData = frameData[(frameData.id == i)]
        x = float(antData['locX'])
        y = float(antData['locY'])
        G.add_node(i, pos=(x, y), label=str(i))
        alarm_strength = row['V' + str(i)]
        colorMap.append(alarm_strength)

    for index, row in interactions.iterrows():
        source, dest = row['AlarmedFrom'], row['Alarmed']
        if not row['Self-Excitation']:
            G.add_edge(source, dest)

    bbox = Bbox(np.array([[0,0],[11,11]]))

    pos = nx.get_node_attributes(G, 'pos')
    nx.draw(G, pos, node_color=colorMap, node_size=10, cmap=plt.cm.Reds, with_labels=True, font_size=10)
    plt.savefig('frames/{}.png'.format(str(frame).rjust(4, '0')))
    plt.clf()

    print('{}/{}'.format(frame, alarmData.Frame.max()))
