#!/usr/bin/env python3
import pandas
import imageio

# alarmData = pandas.read_csv('alarm_strengths.csv')
# #with imageio.get_writer('movie.gif', mode='I') as writer:
# with imageio.get_writer('movie.gif') as writer:
#     #for frame in alarmData.Frame:
#     for frame in range(1, 55):
#         image = imageio.imread('frames/{}.png'.format(frame))
#         writer.append_data(image)

from PIL import Image

#if __name__ == "__main__":
#
#    import sys
#
#    if len(sys.argv) < 3:
#        print("GIFMAKER -- create GIF animations")
#        print("Usage: gifmaker infile outfile")
#        sys.exit(1)
#
#    im = Image.open(sys.argv[1])
#    im.save(sys.argv[2], save_all=True)

images = []

for i in range(1, 30):
    frame = Image.open('frames/{}.png'.format(i))
    images.append(frame)

# Save the frames as an animated GIF
images[0].save('movie.gif',
               save_all=True,
               append_images=images[1:],
               duration=20,
               loop=0)
