#!/usr/bin/env python3
from pprint import pprint
import seaborn as sns
import matplotlib.pyplot as plt
import pandas
import networkx as nx

def read_network():
    propData = pandas.read_csv('propagation.csv')

    interactions = []
    currentDict  = dict()
    time_index  = 0

    for index, row in propData.iterrows():
        time = row.TimeForAlarm
        if time_index < time:
            for i in range(time_index + 1, time):
                interactions.append(dict())
            time_index = time
            interactions.append(currentDict)
            currentDict = dict()
        currentDict[row.AlarmedFrom] = row.Alarmed
    return interactions

def plot_network():
    interactions = read_network()


def main():
    plot_network()

if __name__ == '__main__':
    main()
