#!/usr/bin/env python3
import pandas

from pprint import pprint

alarmData = pandas.read_csv('alarm_strengths.csv')
rows = list(alarmData.iterrows())

width = 10
side_width = width // 2

for i, row in rows:
    window = rows[max(0, i - side_width):i + side_width + 1]
    window = [series for index, series in window]
    averages = sum(window) / len(window)
    alarmData.loc[i] = averages
    print(i)

print(alarmData)
